.\" Manpage for git-outgoing
.TH man 1 "May 2012" "1.0" "git outgoing man page"
.SH NAME
git outgoing \- Show local changesets not on the remote
.SH SYNOPSIS
git outgoing
.SH DESCRIPTION
git outgoing shows all the changes that would be pushed to the remote.
.SH OPTIONS
The outgoing command does not take any options.
.SH SEE ALSO
git(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Stefan Saasen <stefan@saasen.me>
