.\" Manpage for git-stats
.TH man 1 "September 2012" "1.0" "git stats man page"
.SH NAME
git stats\- Show repository statistics
.SH SYNOPSIS
git activity [--gc]
.SH DESCRIPTION
Show basic statistics about the current repository. This command will list the
number of commits, files, objects and contributors and the age of the
repository.
.SH OPTIONS
.TP
.I --gc
Run aggressive gc to get a more accurate object count.
.SH BUGS
No known bugs.
.SH AUTHOR
Stefan Saasen <stefan@saasen.me>
