.\" Manpage for git-incoming
.TH man 1 "May 2012" "1.0" "git incoming man page"
.SH NAME
git incoming \- Show new changesets in the remote
.SH SYNOPSIS
git incoming
.SH DESCRIPTION
git incoming fetches the changes from the default remote and shows the
changesets that would be merged into the current branch if "git pull" would be executed.
.SH OPTIONS
The incoming command does not take any options.
.SH SEE ALSO
git(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Stefan Saasen <stefan@saasen.me>
