.\" Manpage for git-find-blob
.TH man 1 "May 2012" "1.0" "git find-blob man page"
.SH NAME
git find-blob \- Find the commits that contain the given object id
.SH SYNOPSIS
git find-blob <object>
.SH DESCRIPTION
List all the commits that contain the object id <object>
.SH OPTIONS
.TP
.I <object>
Blob object id
.SH SEE ALSO
git(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Stefan Saasen <stefan@saasen.me>
